version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn test
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run semantic-release || true
            fi
